<?php
/**
 * @package languageDefines
 * @copyright Copyright 2003-2022 Zen Cart Development Team
 * Zen Cart German Version - www.zen-cart-pro.at
 * @copyright Portions Copyright 2003 osCommerce
 * @license https://www.zen-cart-pro.at/license/3_0.txt GNU General Public License V3.0
 * @version $Id: ssl_check.php 2022-01-14 16:49:16Z webchills $
 */

define('NAVBAR_TITLE', 'Security Check');
define('HEADING_TITLE', 'Security Check');
define('TEXT_INFORMATION', 'We have detected that your browser has generated a different SSL Session ID than was used throughout our secure pages.');
define('TEXT_INFORMATION_2', 'For security reasons, you will need to logon to your account again to continue shopping online.');
define('TEXT_INFORMATION_3','');
define('TEXT_INFORMATION_4','We have taken this security measure for your benefit, and apologize for any inconvenience it causes.');
define('TEXT_INFORMATION_5','Please contact the store owner if you have any questions relating to this requirement, or to continue purchasing products offline.');
define('BOX_INFORMATION_HEADING', 'Privacy and Security');
define('BOX_INFORMATION', 'We validate the SSL Session ID automatically generated by your browser on every secure page request made to this server.<br /><br />This validation assures that it is you who is navigating on this site with your account and not somebody else.');